export default {
	'rubenbarrero.1985@gmail.com': {
		name: 'RUBEN BARRERO',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'UXBEI1RJG',
	},
	'melinacorapi@gmail.com': {
		name: 'MELINA CORAPI',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '30YICNWAM',
	},
	'valemusica80@gmail.com': {
		name: 'VALERIA ESPINOSA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'ZI2623LBI',
	},
	'nereidaescribano91@gmail.com': {
		name: 'JUANFRAN PEREZ',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: '6G9HXTVGA',
	},
	'sanchezvasquezcarlos14@gmail.com': {
		name: 'KIKE SANCHEZ',
		price: '25 dolares',
		price_id: 'price_1Oc4tkAhFKbqBWSpXXRKexym',
		code: 'IOLTCXAR0',
	},
	'sergivazquezsimo@gmail.com': {
		name: 'SERGI VAZQUEZ',
		price: '50 euros',
		price_id: 'price_1Oc4usAhFKbqBWSpLpeBkDEr',
		code: 'OUDW44ECV',
	},
	'ivanagurain@gmail.com': {
		name: 'IVAN AGURAIN',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: '3CKSIS9IO',
	},
	'cecimacanek@gmail.com': {
		name: 'CECI MACANEK',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '0C8JA9VX0',
	},
	'mportizclaraco@gmail.com': {
		name: 'PILAR ORTIZ',
		price: '50 euros',
		price_id: 'price_1Oc4usAhFKbqBWSpLpeBkDEr',
		code: '9MEL5AOLL',
	},
	'eugesosacima@gmail.com': {
		name: 'EUGE SOSA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'TNEBBY6U4',
	},
	'renata.pinedovaldiviezo@gmail.com': {
		name: 'RENATA PINEDO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '8TM9EFA4I',
	},
	'thais.grancha@gmail.com': {
		name: 'THAIS GRANCHA',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'LHBGMQZKA',
	},
	'1959xily@gmail.com': {
		name: 'XILI NODA',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'EO99H9D8B',
	},
	'orellanogabriela76@gmail.com': {
		name: 'GABRIELA ORELLANO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'VY93B7UWA',
	},
	'soledadwinter79@gmail.com': {
		name: 'SOLEDAD WINTER',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'C7MU5NLL0',
	},
	'dario.sastre84@gmail.com': {
		name: 'DARIO SASTRE',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'B3UAKJH0V',
	},
	'javiertillous2016@gmail.com': {
		name: 'JAVIER TILLOUS',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'IWC1KWMD0',
	},
	'pmacanek@gmail.com': {
		name: 'PABLO MACANEK',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'N02LHBJ94',
	},
	'marilusalazar.bv@gmail.com': {
		name: 'MARILU SALAZAR',
		price: '30 dolares',
		price_id: 'price_1Oc4u9AhFKbqBWSp7IiKIymX',
		code: '89FP8XS4I',
	},
	'ataraxia.omens22@gmail.com': {
		name: 'JONATAN FULLONE',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'JEHW3PV1X',
	},
	'virginiamacaroni@gmail.com': {
		name: 'VIRGINIA MACARONI',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'S1IDH5Z82',
	},
	'mgamioe@gmail.com': {
		name: 'MACARENA GAMIO',
		price: '30 dolares',
		price_id: 'price_1Oc4u9AhFKbqBWSp7IiKIymX',
		code: 'GX6L0OPFQ',
	},
	'anagonzalezlopez85@gmail.com': {
		name: 'ANA GONZALEZ',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'Q8LJN7Q3A',
	},
	'ionanderlomas@gmail.com': {
		name: 'ION ANDER',
		price: '50 euros',
		price_id: 'price_1Oc4usAhFKbqBWSpLpeBkDEr',
		code: 'CB9OWLRDY',
	},
	'micaela.barrios@gmail.com': {
		name: 'MICAELA BARRIOS',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'MX50CQEXG',
	},
	'leocaleta4@gmail.com': {
		name: 'LEO CALETA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '99CX5U8OM',
	},
	'cfc9085@gmail.com': {
		name: 'CARLA CASTRO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'U5J89VHTL',
	},
	'garcesj846@gmail.com': {
		name: 'JORGE GARCES',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'W2N3B308I',
	},
	'juanantoniosierrarana@gmail.com': {
		name: 'ANTONIO SIERRA',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'Z8G5CQ942',
	},
	'laucastro@gmail.com': {
		name: 'LAURA CASTRO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'QM77CH63R',
	},
	'egamioa@gmail.com': {
		name: 'ENRIQUE GAMIO',
		price: '30 dolares',
		price_id: 'price_1Oc4u9AhFKbqBWSp7IiKIymX',
		code: 'EGT0W94DI',
	},
	'julietacabrera33@gmail.com': {
		name: 'JULIETA CABRERA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'CFBV2OZXQ',
	},
	'garonajoaquin@gmail.com': {
		name: 'JOAQUIN GARONA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '2DHM00OZX',
	},
	'jdallorsoacs@gmail.com': {
		name: 'JUAN DALL´ORSO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'WXP5ZACKY',
	},
	'mluzlago.212@gmail.com': {
		name: 'LUZ LAGO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'ZU9OVZMBE',
	},
	'estelareyes71@gmail.com': {
		name: 'ESTELA REYES',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'XTQLK9EFY',
	},
	'mendozagerardolionel@gmail.com': {
		name: 'LIO MENDOZA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'FMEO4PYBJ',
	},
	'hfrias1979@gmail.com': {
		name: 'HORACIO FRIAS',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'BJVPTZBYL',
	},
	'dariohernanc81@gmail.com': {
		name: 'DARIO CASTRO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'TRX7GU9QX',
	},
	'vilmaguat@gmail.com': {
		name: 'VILMA PRECIADO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'N6UKZJOVT',
	},
	'pablogirald@gmail.com': {
		name: 'PABLO GIRALDO',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'M2SX4AFUY',
	},
	'mnsoria@gmail.com': {
		name: 'NATALIA SORIA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'QKA2PO228',
	},
	'agusmartins@gmail.com': {
		name: 'AGUSTIN MARTINS',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '0DC65X221',
	},
	'denislmn@gmail.com': {
		name: 'DENISE NODA',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'CIDRSMWYB',
	},
	'beluperez2303@gmail.com': {
		name: 'NOELIA PEREZ',
		price: '50 euros',
		price_id: 'price_1Oc4usAhFKbqBWSpLpeBkDEr',
		code: 'O8SLBKLTA',
	},
	'negroakd@gmail.com': {
		name: 'MARTIN URQUIZA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'ME706UKSU',
	},
	'ferranvilarooliana@gmail.com': {
		name: 'FERRAN VILARO',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'QFCNF7I66',
	},
	'doncelabadmarcos@gmail.com': {
		name: 'MARCOS DONCEL',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'UD8R06T0H',
	},
	'ramosalejandra150@gmail.com': {
		name: 'ALEJANDRA RAMOS',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'PDDYVHEZY',
	},
	'mauricioolivers1980@gmail.com': {
		name: 'MAURICIO OLIVERA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'SKFT53RTT',
	},
	'mmilara1@gmail.com': {
		name: 'MARIA MILARA',
		price: '80 euros',
		price_id: 'price_1Oc4waAhFKbqBWSp0CQuYh5k',
		code: 'Z9MIXA0JB',
	},
	'luchopelliccia@gmail.com': {
		name: 'LUCIANO PELLICCIA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '9T53O9BF7',
	},
	'hdez2jr@gmail.com': {
		name: 'JESUS HERNANDEZ',
		price: '50 euros',
		price_id: 'price_1Oc4usAhFKbqBWSpLpeBkDEr',
		code: '9XOP31BK9',
	},
	'malena.trufo3@gmail.com': {
		name: 'MALENA TRUFO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'MDG0XA66K',
	},
	'rosarioalvarez847@gmail.com': {
		name: 'ROSARIO ALVAREZ',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'ZBFTAY4F2',
	},
	'kilianpf@gmail.com': {
		name: 'KILIAN PADRON',
		price: '50 euros',
		price_id: 'price_1Oc4usAhFKbqBWSpLpeBkDEr',
		code: 'Z8GJBQG25',
	},
	'miguelgrandoli29@gmail.com': {
		name: 'MIGUEL GRANDOLI',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '8PYAREGUP',
	},
	'martiiris739@gmail.com': {
		name: 'MARTA PERITO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'TDSHLE9VA',
	},
	'raultrail1980@gmail.com': {
		name: 'RAUL CASTILLO',
		price: '50 euros',
		price_id: 'price_1Oc4usAhFKbqBWSpLpeBkDEr',
		code: 'ATNKAA0KT',
	},
	'ftascongonzalez@gmail.com': {
		name: 'FRANCISCO TASCON',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: '0PPOTZWWX',
	},
	'dhutreras@gmail.com': {
		name: 'DAVID HERNANDEZ',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'Q3CH5JMI3',
	},
	'ludmilasantillan2022@gmail.com': {
		name: 'LUDMILA SANTILLAN',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'ZWEWXE3UT',
	},
	'higlebrito@gmail.com': {
		name: 'HIGLE BRITO',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'RE151H1C2',
	},
	'edisa12@gmail.com': {
		name: 'EDISA DOMINGUEZ',
		price: '25 dolares',
		price_id: 'price_1Oc4tkAhFKbqBWSpXXRKexym',
		code: 'LXY8KV7NJ',
	},
	'avagonal@gmail.com': {
		name: 'ANDREA AGONAL',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '6FWS3A0OH',
	},
	'larsnow@gmail.com': {
		name: 'MARC LARSNOW',
		price: '50 euros',
		price_id: 'price_1Oc4usAhFKbqBWSpLpeBkDEr',
		code: 'FO720VQY5',
	},
	'juanjosegismundo@gmail.com': {
		name: 'JUANJO SEGIS',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'CQ27Z508Q',
	},
	'nadia.ricci683@gmail.com': {
		name: 'NADIA RICCI',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'BCJM2CQZ6',
	},
	'eriksalas933@gmail.com': {
		name: 'ERIK SALAS',
		price: '50 euros',
		price_id: 'price_1Oc4usAhFKbqBWSpLpeBkDEr',
		code: 'QI1WGTB97',
	},
	'samuelverab@gmail.com': {
		name: 'SAMUEL VERA',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: '0H9HA71Y6',
	},
	'torreselsaines@gmail.com': {
		name: 'ELSA TORRES',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'ULLGV43QP',
	},
	'j.a.ortega5189@gmail.com': {
		name: 'JOSAN ORTEGA',
		price: '50 euros',
		price_id: 'price_1Oc4usAhFKbqBWSpLpeBkDEr',
		code: 'W2L6VZ5TP',
	},
	'adrianftv@gmail.com': {
		name: 'ADRIAN PADRON',
		price: '50 euros',
		price_id: 'price_1Oc4usAhFKbqBWSpLpeBkDEr',
		code: 'ZQKEUZZIS',
	},
	'peralta.paula.3219@gmail.com': {
		name: 'PAULA PERALTA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '8HRTMFEBP',
	},
	'zamijap88@gmail.com': {
		name: 'ZAMI ARDILA',
		price: '25 dolares',
		price_id: 'price_1Oc4tkAhFKbqBWSpXXRKexym',
		code: 'DUQ9FABTY',
	},
	'veronicasavino3@gmail.com': {
		name: 'VERO SAVINO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '6AGPLO7OU',
	},
	'celiabaldovino@gmail.com': {
		name: 'CELIA BALDOVINO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'CP778W9Q9',
	},
	'patripereyra790@gmail.com': {
		name: 'PATRICIA PEREYRA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'T813906EZ',
	},
	'caromedina634@gmail.com': {
		name: 'CARO MEDINA',
		price: '25 dolares',
		price_id: 'price_1Oc4tkAhFKbqBWSpXXRKexym',
		code: '5VQU3XFHF',
	},
	'juanmanuelriveros777@gmail.com': {
		name: 'JUAN RIVEROS',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '64JVF8ERO',
	},
	'dafnecelinamanavella@gmail.com': {
		name: 'DAFNE MANAVELLA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '4Y5ER5D4W',
	},
	'ljgambande@gmail.com': {
		name: 'LUCIO GAMBANDE',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'Z8KL58KLB',
	},
	'brec.locke@gmail.com': {
		name: 'BREIXO LOPEZ',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'X8S7FC5GQ',
	},
	'fabianarodriguezferrari@gmail.com': {
		name: 'FABIANA RODRIGUEZ',
		price: '25 dolares',
		price_id: 'price_1Oc4tkAhFKbqBWSpXXRKexym',
		code: 'IOLGMKBK8',
	},
	'alvarezsimona24@gmail.com': {
		name: 'SIMONA ALVAREZ',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'QP26Y3BHQ',
	},
	'ernloza@gmail.com': {
		name: 'ERNESTO LOZA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'WTXUNLDI5',
	},
	'bettinaalfon@gmail.com': {
		name: 'BETTINA ALFONSO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'NDRUHIU3I',
	},
	'sgarciamerino7@gmail.com': {
		name: 'SARA GARCIA',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: '7CZWX7KDR',
	},
	'jgomezrequena@gmail.com': {
		name: 'JORDI GOMEZ',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'WAOOSRIQG',
	},
	'victorcruzmonzon@gmail.com': {
		name: 'VICTOR MONZON',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'FE2Y192IB',
	},
	'airamtrailrunner@gmail.com': {
		name: 'AIRAM ALONSO',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: '6ZIV5G9TV',
	},
	'marcelaorozco422@gmail.com': {
		name: 'MARCELA OROZCO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'IAWHN2YN5',
	},
	'cardinalijs@gmail.com': {
		name: 'SEBASTIAN CARDINALI',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '8FZY6RNJD',
	},
	'hectorfuenzalida629@gmail.com': {
		name: 'HECTOR FUENZALIDA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '6HZQ9D0FR',
	},
	'federico.mayer@clubagtech.com': {
		name: 'FEDERICO MAYER',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'I19WYGLUS',
	},
	'nicomoore@gmail.com': {
		name: 'NICOLAS MOORE',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '3J6ZFQDIH',
	},
	'nildareynoso541@gmail.com': {
		name: 'NILDA REYNOSO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '7P3HNP4ME',
	},
	'maria.laulne@gmail.com': {
		name: 'MARIA BARRETO',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'XGGREWD5K',
	},
	'fernando.banoscuria@gmail.com': {
		name: 'FERNANDO BAÑOS',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'YFSJ37VVB',
	},
	'valejm009@gmail.com': {
		name: 'ALEJANDRA MARTINEZ',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'QHQ026SH9',
	},
	'melissabaiza0@gmail.com': {
		name: 'MELISSA BAIZA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'PI7AEYR50',
	},
	'rociodavina@gmail.com': {
		name: 'ROCIO DAVIÑA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '8PTIM3J11',
	},
	'karofranco63@gmail.com': {
		name: 'KARINA FRANCO',
		price: '16.000 pesos',
		price_id: 'price_1Oc4qMAhFKbqBWSpHm7GrAJu',
		code: 'ZANPLR2XN',
	},
	'ezequiel291009@gmail.com': {
		name: 'EZEQUIEL RODRIGUEZ',
		price: '16.000 pesos',
		price_id: 'price_1Oc4qMAhFKbqBWSpHm7GrAJu',
		code: 'M8XL6I6A5',
	},
	'mikelqsanchez@gmail.com': {
		name: 'MIKEL SANCHEZ',
		price: '50 euros',
		price_id: 'price_1Oc4usAhFKbqBWSpLpeBkDEr',
		code: 'N6TYNVRH5',
	},
	'nataliaguido15@gmail.com': {
		name: 'NATALIA GUIDO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '8F7AEDBVK',
	},
	'ali.3891842@gmail.com': {
		name: 'ALISON HERNANDEZ',
		price: '25 dolares',
		price_id: 'price_1Oc4tkAhFKbqBWSpXXRKexym',
		code: '4V2XE3MDH',
	},
	'cuellopaula282@gmail.com': {
		name: 'PAULA CUELLO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '2UYZ106N3',
	},
	'luismfirpo@gmail.com': {
		name: 'LUIS FIRPO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'CIVK418AI',
	},
	'rosiriv@gmail.com': {
		name: 'ROSALIA RIVEROS',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'FY1RZLZXW',
	},
	'lilianabeatrize1976@gmail.com': {
		name: 'LILIANA ESPINDOLA',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '7SGZGHUUK',
	},
	'danielalfa2002@gmail.com': {
		name: 'DANIEL RUIZ DIAZ',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'W9689DTHP',
	},
	'horaciobaldovino@gmail.com': {
		name: 'HORACIO BALDOVINO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'T6JPRF3T0',
	},
	'victorsaulaquino@gmail.com': {
		name: 'SAUL AQUINO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'S5TBATLP6',
	},
	'danisabulgarelli33@gmail.com': {
		name: 'DANISA BULGARELLI',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'ASU1BHSQG',
	},
	'artur.nico@gmail.com': {
		name: 'ARTURO AGUILAR',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '58LDXJPAY',
	},
	'lucianomasarotti@gmail.com': {
		name: 'LUCIANO MASAROTTI',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'JB3GIPHA4',
	},
	'santiagoardanaz@gmail.com': {
		name: 'SANTIAGO ARDANAZ',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '756OAVQUZ',
	},
	'vicentediego567@gmail.com': {
		name: 'DIEGO VICENTE',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '1ZLYC4F51',
	},
	'lilianalujanzanetti@gmail.com': {
		name: 'LILIANA ZANETTI',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'C7TUNTWCA',
	},
	'martinosoledad218@gmail.com': {
		name: 'SOLEDAD MARTINO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'HV7C3F9GQ',
	},
	'erneshuasi@gmail.com': {
		name: 'LORENA ESCOBAR',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: '13V4NKFIV',
	},
	'dianamiramontes.inda@gmail.com': {
		name: 'DIANA MIRAMONTES',
		price: '30 dolares',
		price_id: 'price_1Oc4u9AhFKbqBWSp7IiKIymX',
		code: '1OYWWQ52A',
	},
	'bravomarialaura432@gmail.com': {
		name: 'MARIA LAURA BRAVO',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'MOZ0CSCLF',
	},
	'lorenavsk92@gmail.com': {
		name: 'LORENA VERA',
		price: '50 euros',
		price_id: 'price_1Oc4usAhFKbqBWSpLpeBkDEr',
		code: '8RLKY77KJ',
	},
	'sfmaudet@gmail.com': {
		name: 'SANTIAGO MAUDET',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: '6U3MWC1GN',
	},
	'irvinelo1231@gmail.com': {
		name: 'IRVING SANCHEZ',
		price: '30 dolares',
		price_id: 'price_1Oc4u9AhFKbqBWSp7IiKIymX',
		code: 'QU307K9GR',
	},
	'cmeza13@gmail.com': {
		name: 'CARLOS JIMENEZ',
		price: '30 dolares',
		price_id: 'price_1Oc4u9AhFKbqBWSp7IiKIymX',
		code: '3K2MZI6MB',
	},
	'jadobons7@gmail.com': {
		name: 'ANTONIO BONS',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: '61GHHHPJ5',
	},
	'igaldonaluis@gmail.com': {
		name: 'IRYMA GALDONA',
		price: '40 euros',
		price_id: 'price_1Oc4vbAhFKbqBWSptrVCmAOX',
		code: 'JIM27JQ4R',
	},
	'ramirezmejia1989@gmail.com': {
		name: 'MARTIN RAMIREZ',
		price: '25 dolares',
		price_id: 'price_1Oc4tkAhFKbqBWSpXXRKexym',
		code: '8BK49Y0B8',
	},
	'mitxarro79@gmail.com': {
		name: 'XABIER PEREZ',
		price: '50 euros',
		price_id: 'price_1Oc4usAhFKbqBWSpLpeBkDEr',
		code: '84WFM0ANU',
	},
	'benitezflavia@gmail.com': {
		name: 'FLAVIA BENITEZ',
		price: '50 euros',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'I9Z5NH6YV',
	},
	'juandelafenetre@gmail.com': {
		name: 'JUAN DELAFENETRE',
		price: '21.000 pesos',
		price_id: 'price_1Oc4rTAhFKbqBWSp8X46Cmaf',
		code: 'SL87JSDX',
	},
};
